### ISSUE TITLE
Is it possible to use it without expo?

### ISSUE THREAD

**Issue by maciekstosio** [reggie3/react-native-webview-quilljs#12]
I tried to use it with react-native (after int) but I'm getting error `Unable to resolve module 'expo' ...` .

**Comment by reggie3** [comment]
Try installing the Expo SDK's using the steps [here](https://github.com/expo/xde#converting-an-existing-project-to-work-with-expo)

**Comment by reggie3** [comment]
Also, I'm working on making it not require Expo, but I'm having some trouble getting it bundled in an Expo package for deployment.  However, if you're not using Expo, then it might be what you're looking for.  You can try this latest beta which does not require any Expo dependencies to run by installing the beta using `npm install react-native-webview-quilljs@beta`.  I'd appreciate any feedback you have.

**Comment by khizarvaio** [comment]
I've installed this specific like you mentioned version npm install react-native-webview-quilljs@beta.
Don't know it still showing the same exception.

**Comment by whitesnow9291** [comment]
Hi reggie, would you please let me know if this solved?
