### ISSUE TITLE
Confirm Inline Javascript Version Works in Non-Expo React Native Projects

### ISSUE THREAD

**Issue by reggie3** [reggie3/react-native-webview-quilljs#14]
I've confirmed that the beta version of this library built using inline JavaScript, and currently published on npm `@beta` works in React Native applications built using Expo.  However I need confirmation that the library also works in regular React Native applications (or not).
The beta version can be installed using `npm install react-native-webview-quilljs@beta`
I'd appreciate any help anybody can give me in figuring out whether this library works as I hope.

**Comment by dgurns** [comment]
I just tried installing the beta in my non-Expo app. It's not working and I'm getting this error:

> (node:27390) UnhandledPromiseRejectionWarning: Error: Unable to resolve module `expo` from `/Users/......./node_modules/react-native-webview-quilljs/WebViewQuillEditor.js`:Module `expo` does not exist in the Haste module map

My version of the package is `"react-native-webview-quilljs": "^0.8.35"` – is that the correct beta version?

**Comment by reggie3** [comment]
I've included Expo as a dependency in the latest version. Please update and try again.
