### ISSUE TITLE
onLoad callback does not fire

### ISSUE THREAD

**Issue by foysalit** [reggie3/react-native-webview-quilljs#15]
Also, htmlContentToDisplay prop doesnt seem to be working either and I can't figure out how to debug this since the source is now minified. Any clue on how to debug this so I can fix it and send a PR? A contribution guide would be great. Thanks

**Comment by reggie3** [comment]
I just updated the package.  Beta version 0.6.16 should fix the onLoad callback.  I also got rid of the minification, and added sourcemaps that hopefully aid in debugging.

I'm assuming you're using the Beta version.  Please let me know if it was working for you otherwise.  I'd like to merge it to master and publish it, but I need to know if inlining the JavaScript is causing problems.

**Comment by foysalit** [comment]
Yeah you're right, I'm using the beta version and everything seems to be working with 0.6.16.... *except* for the htmlContentToDisplay prop. I have tried setting the prop with html content but it's just not working. Could you please take a look at the PR I sent and see if you can find out why it's not working with your version? I'm certain that it was working with the code I wrote for that PR. Thanks in advance.

**Comment by reggie3** [comment]
I've updated the master branch to the newest version.  I'm trying to implement some testing so the library doesn't get broken as features are added to it.  Are you experienced with testing, and if so, could you help me write a test that ensures htmlContentToDisplay works (and continues to work) as advertised?

**Comment by reggie3** [comment]
The updated version in the "master" branch has the code from the pull request.  Please, let me know if it's not working correctly.

**Comment by jaspal-singh-gulati** [comment]
Is It possible to get the content of the editor in HTML format?

**Comment by reggie3** [comment]
This project uses [Quill.js](https://github.com/quilljs/quill) which returns uses Deltas for content storage.  Return HTML would be beyond the scope of this project.  However, you might want to take a look at this package which does conversions [quill-delta-to-html](https://github.com/nozer/quill-delta-to-html)
