### ISSUE TITLE
Add Placeholder 

### ISSUE THREAD

**Issue by jaspal-singh-gulati** [reggie3/react-native-webview-quilljs#18]
Please provide the prop for setting the placeholder.

**Comment by reggie3** [comment]
What do you mean?

**Comment by udarts** [comment]
I would also like to be able to add a placeholder on the view and editor. Just a temporary text and when you click on the field to edit, the placeholder is going, but when removing all the text, the placeholder should be back. Also adding style to that place holder would be nice.

**Comment by udarts** [comment]
@reggie3 is this possible?

**Comment by reggie3** [comment]
Yes, you want the contentToDisplay prop that is available both components.

**Comment by udarts** [comment]
But that is not a real placeholder. With a placeholder, when you focus the field or when you start typing, it removes the placeholder. At this moment, you need to remove the text, before you can add your own. If you get what I mean?

**Comment by reggie3** [comment]
Okay, now I understand what you're looking for.  That is not currently supported.
