### ISSUE TITLE
Text too Small on iPhone

### ISSUE THREAD

**Issue by reggie3** [reggie3/react-native-webview-quilljs#2]
Text in the editor and viewer appear correctly on Android devices, but is too small on iPhone (and presumably other iOS devices).  The fontSize style property appears to be ignored.

**Comment by reggie3** [comment]
Fixed in version 0.3.0

**Comment by mukeshsoni** [comment]
Hey @reggie3 ! I am trying to wrap `react-draft-wyiswyg` in a webview and am getting the same problem of tiny fonts on iOS.  I tried go through the styles in the file which as WebView as well as the file which gets rendered in the WebView (with Quilljs), but couldn't get a clue on what worked.

Can you please tell how you fixed it?

**Comment by reggie3** [comment]
I was able to fix it by adding `scalesPageToFit={false}` to the props of the WebView.

**Comment by mukeshsoni** [comment]
Thank you so much @reggie3 ! Appreciate your help.

Also thanks for your blog posts. Helped me a lot.

Can i ask another question if you don't mind answering? Why did you use a queue for posting messages from the editor inside the webview?

**Comment by mukeshsoni** [comment]
Ah ok, yeah saw the acknowledgement part. Thanks for clarifying!

I was thinking about creating an abstraction around all the message passing so that someone else can use the new `EnhancedWebview` just like any other react component, with a few instance methods which return promises (e.g. this.webviewRef.getContent().then()). Don't know if it's possible. Just an idea.

**Comment by reggie3** [comment]
So, previously I used this package: https://github.com/R1ZZU/react-native-webview-messaging which does abstract the messaging passing.  I stopped using it because it was having problems with iOS devices at the time (about 2 months ago) I don't know the project's current status.  Maybe you can help on that project.  I've contributed to it before, and the developer is easy to work with.

**Comment by mukeshsoni** [comment]
Interesting! Will check it out. The API can probably be made more react like by doing things through props and not by creating a complete event system by using the ref. Thanks for the link!
