### ISSUE TITLE
WebViewQuillEditor has no height so does not render

### ISSUE THREAD

**Issue by pdkn** [reggie3/react-native-webview-quilljs#23]
the internal views of WebViewQuillEditor only has flex:1. When adding to a screen nothing is rendering as no height is getting calculated. (react-native 0.54) be useful for override styles to be set i.e 

`const EDITOR: ViewStyle = {
  ...StyleSheet.absoluteFillObject,
  height:450,
  top:50,
}`

`...
render() {
    return (
      <View style={FULL}>
            <WebViewQuillEditor
              overrideStyles={EDITOR}
              ref={component => (this.webViewQuillEditor = component)}
              getDeltaCallback={this.getDeltaCallback}
              backgroundColor="green"
              contentToDisplay={this.contentToDisplay}
              onLoad={this.onLoadCallback}
            />....`

and in WebViewQuillEditor

`...
render = () => {
    return (
      <View
        style={{
          ...{flex: 1},
          ...this.props.overrideStyles
        }}
      >...`

**Comment by reggie3** [comment]
@pdkn Are you putting the editor inside of a component that has height?  For example the example in the App.js file of the repo has the editor inside a flex component like this:

```
<View
          style={{
            flex: 1,
            padding: 5,
            backgroundColor: 'red'
          }}
        >
          <WebViewQuillEditor
            ref={component => (this.webViewQuillEditor = component)}
            getDeltaCallback={this.getDeltaCallback}
            onDeltaChangeCallback={this.onDeltaChangeCallback}
            backgroundColor={'#fffbea'}
          />
</View>
```

**Comment by pdkn** [comment]
I have it within a 'Screen' view not flex'ed where I want to position it. Adding it to a subview works, thanks. Still, ideally, being able to override and set styles directly on it would be handy, considering it's already wrapped in a view internally. Could I encourage you to look into it? thanks again

**Comment by reggie3** [comment]
I think it is a good idea.  Would you be willing to submit a pull request for it?
