### ISSUE TITLE
Toolbar not showing on Android 4.4 (API 19)

### ISSUE THREAD

**Issue by udarts** [reggie3/react-native-webview-quilljs#24]
The toolbar is not showing on Android 4.4 (api 19).
I use the general setup.

Any idea why?

Cheers,

**Comment by udarts** [comment]
@reggie3, do you know what the minimum version of Android is, where this plugin is working on? I have tested it on: api 19 (not working, not showing the toolbar) and api 23 (showing the toolbar and seems to work).

**Comment by udarts** [comment]
It seems to be stuck at the LOAD_EDITOR, not continuing after that.
At the moment this is only happening on Android API 19 (4.4).

**Comment by reggie3** [comment]
I don't know why it's not working.  According to the React Native GitHub page, RN supports Android API 16 and up.  What other versions have you used it on?  Have you tried it with any other version prior to API 19.  That is when a new Android introduced a new WebView based on Chromium.

https://developer.android.com/guide/webapps/migrating

**Comment by udarts** [comment]
Hmm, very strange. I have tested in on Android API 23 and 27 and both work. I have also asked on Stackoverflow, maybe someone there can help out.

**Comment by udarts** [comment]
@reggie3 I have also tried it with version 18 and also not working. I am wondering what changed from 19 and prior, that doesn't make it work in older versions.

**Comment by reggie3** [comment]
I don't know, but I'll leave this issue open just in case someone finds a solution.

**Comment by reggie3** [comment]
Closing due to lack of response.
