### ISSUE TITLE
Not working in production

### ISSUE THREAD

**Issue by udarts** [reggie3/react-native-webview-quilljs#25]
@reggie3 I have been trying to use the plugin, on development it works on most devices. But when I push it to production (and test it with a select group of people), the loading indicator is all that is showing. This happens on ios and android.

Have you encountered this on production?

Cheers,

**Comment by reggie3** [comment]
Can you be more specific about what you mean when you say production?  Are you publishing it in the store, or publishing it via Expo?

**Comment by mehrapratham** [comment]
I am publishing it via Expo and getting the same issue.

**Comment by reggie3** [comment]
Closing this issue.  This problem also affects another package that I built, and will be tracked there.  Here is the link: https://github.com/reggie3/react-native-webview-leaflet/issues/33.
