### ISSUE TITLE
Can't get the content of the editor.

### ISSUE THREAD

**Issue by ewein** [reggie3/react-native-webview-quilljs#27]
I'm using the new beta version (0.6.18). I can't seem to get the content from the editor. My component is defined as:

```
    <WebViewQuillEditor
         ref={component => { this.webViewQuillEditor = component} }
         getDeltaCallback={this.getDeltaCallback}
    />

    getDeltaCallback = (delta) => {
        console.log('--------------------');
        console.log(delta);
        console.log('--------------------');
    }
```
 When I call `this.webViewQuillEditor.getDelta();` I don't get anything printing out. Any idea what is going on here? I'm running the app via Expo CLI and on a physical Android device.

**Comment by Rupinderthind** [comment]
USE THIS

getDeltaCallback = (delta) => {
      console.log('--------------------');
      console.log(delta);
      console.log('--------------------');
  }
getData(){
     let data = this.webViewQuillEditor.getDelta();
}

hit getData function on press of any TouchableOpacity in react native

**Comment by saurabhabh** [comment]
Is this working ? I am also not able to get the content of the editor
