### ISSUE TITLE
How to use without Expo?

### ISSUE THREAD

**Issue by arminghm** [reggie3/react-native-webview-quilljs#30]

**Comment by reggie3** [comment]
For now, use without Expo is not supported.

**Comment by ActionJ4ckson** [comment]
Hey @reggie3 
Just wondering if there is any update on it now?
Could you please elaborate your comment- "You can fork the project in order to remove the Expo dependency. Several people have already forked it in order to do just that, and you can reach their forks via the GitHub repository. The editing toolbar is currently not configurable."?

https://medium.com/@reginald.johnson/introducing-react-native-webview-quilljs-e6ca0d13c45c

**Comment by morenoh149** [comment]
@ActionJ4ckson did you try it? where did you get stuck? share code via GitHub repo so we can test it

**Comment by risingworld777** [comment]
You can use it with `react-native-unimodules` and `react-native-webview` on bare react native project.

**Comment by reggie3** [comment]
@risingworld777 can you explain how that would work?  I've never used react-native-unimodules before.

**Comment by risingworld777** [comment]
@reggie3  You can find more information [here](https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331). 
First, I installed `react-native-unimodules` but got error when import library. 
Then installed `react-native-webview` and issue was resolved.

**Comment by Taz742** [comment]
> @reggie3 You can find more information [here](https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331).
> First, I installed `react-native-unimodules` but got error when import `react-native-webview-quilljs` library.
> Then installed `react-native-webview` and issue was resolved.

@risingworld777 How did you do it? I'v installed all the packages which you said, but I can't write it anything.

Here are the image: https://ibb.co/fDDwxwG

**Comment by ActionJ4ckson** [comment]
> @ActionJ4ckson did you try it? where did you get stuck? share code via GitHub repo so we can test it

Hey @morenoh149 
Thanks for checking. It is discussed in the comments here... 
https://github.com/reggie3/react-native-webview-quilljs/commit/6e53fd2832e71e4ab92117c1a9515c6652ee160a#commitcomment-33314611

**Comment by Taz742** [comment]
@ActionJ4ckson Did you find any solution to remove expo dependencies?

**Comment by risingworld777** [comment]
@Taz742  It is working fine on my side.  By the way my project was ejected from Expo and it is still using expo libraries. Of course, I am using `react-native-webview-quilljs` library.
I think you need to ask further issues to @reggie3

**Comment by Lg0gs** [comment]
@risingworld777 
we don't use an ejected version and could this be a problem?

**Comment by risingworld777** [comment]
@Lg0gs  I haven't tried from non-ejected version yet. My project was ejected from Expo and now it is not expo project.
