### ISSUE TITLE
Unable to run demo on pure react native project

### ISSUE THREAD

**Issue by NiveshShastri** [reggie3/react-native-webview-quilljs#36]
I have tried with the new version of the repository (0.8.41), but I am getting below issue while running demo:
`unable to resolve module expo-file-system from /node_modules/expo-asset-utils/src/copyAssetToSameDirectorWithNewNameAsync.js
`

**Comment by NiveshShastri** [comment]
@reggie3 It would be great if you resolve the issue.

**Comment by AdityaSantoso** [comment]
Seems like the simplest way to resolve this is to also install the whole unimodules to make use of expo API 
`yarn add react-native-unimodules`

https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331

**Comment by NiveshShastri** [comment]
@AdityaSantoso I don't want to add whole react-native-unimodules into the app.

**Comment by NiveshShastri** [comment]
@reggie3 is there any update on this

**Comment by reggie3** [comment]
This project relies on certain expo libraries and won't work without them.
