### ISSUE TITLE
Editor not shown on latest version 

### ISSUE THREAD

**Issue by AdityaSantoso** [reggie3/react-native-webview-quilljs#37]
This revision seems to be the one that is pushed to npm: 
https://github.com/reggie3/react-native-webview-quilljs/commit/ab624e9e807bb5ec42e54442286609a19c0cedda#diff-969ac6acd31f53a2f16a01e1d7f7bb74 

In line 179, this line: this.state.editorIndexFileAsset is always falsey, because editorIndexFileAsset is never set. The editor will never be shown

**Comment by AdityaSantoso** [comment]
The file reactQuillViewer-index.html is also corrupt because it contains unresolved merge conflict

**Comment by wontwon** [comment]
I am unable to get the editor to display as well

**Comment by reggie3** [comment]
Fixed in version 2
