### ISSUE TITLE
I love what you're doing here, but I wasn't able to get the app to work via expo on any platform

### ISSUE THREAD

**Issue by jacklinton** [reggie3/react-native-webview-quilljs#5]
I tried on a new iPhone, an old iPad, and a new Kindle HD. I couldn't get a keyboard to appear or enter any text.

**Comment by reggie3** [comment]
Are you running the app that was published on Expo.  If so,can you try it again? I was testing an updated asset bundling system, and it did not work.
Otherwise, if you're not running the Expo published version, how are you running it?

**Comment by jacklinton** [comment]
Yes I was using it through expo. It seems to be working on man iPhone 8n Plus now! Excellent work.

Jack

**Comment by jacklinton** [comment]
No dice getting it work on Android though, on my Kindle or a Google Nexus 5 Sim. It did work beautifully on my iPad.

**Comment by reggie3** [comment]
I'm currently using it on a OnePlus 5 Android device successfully.  I'll be able to test it on a few more devices in a couple of days to see if I can figure it out.

**Comment by reggie3** [comment]
I just tried it on a Nexus 6 and iPhone and it was working correctly (except for small font on the iPhone).  Are you still running into problems with it?
