### ISSUE TITLE
How to use it without expo?

### ISSUE THREAD

**Issue by iksent** [reggie3/react-native-webview-quilljs#7]
After installing package with `yarn add`, I got this error:

error: bundling failed: Error: Unable to resolve module `expo` from `C:\Android\dev\crm_mobile_react_native\node_modules\react-native-webview-quilljs\WebViewQuillEditor.js`: Module does not exist in the module map

So how to use it without installing expo?

**Comment by reggie3** [comment]
The module us s Expo for filesystem read and write, so right now it can't be used without Expo.

**Comment by iksent** [comment]
Then we can use your component only in very rare cases. In real projects it is impossible to use Expo and not to use native modules. Very disappointing.

**Comment by reggie3** [comment]
That might be correct, and if so, it is a limitation.
