### ISSUE TITLE
Content won't display in Viewer component

### ISSUE THREAD

**Issue by jacklinton** [reggie3/react-native-webview-quilljs#9]
I have my editor and my viewer in separate components. The editor works perfectly - it pops up as a modal and when it submits, it sends the object off to an external API after stringifying it. Then, when the display component loads, the API is called to get the object back. On success, a state change is triggered which calls the viewer to render, which it does. The problem is that nothing will display inside the viewer. I even tried putting the object directly in the contentToDisplay prop. Still nothing shows up inside the viewer.

Here's the code that renders the viewer once the API responds and the response is set to the state...
```
<View style={{
                    flex: 1,
                    padding: 5}}>
                    {this.state.apiRes && <WebViewQuillViewer
                        ref={component => (this.webViewQuillViewer = component)}
                        contentToDisplay={JSON.parse(this.state.myxInput)}
                        // onLoad={this.onLoadCallback()}
                    />}
                </View>
```

Here's what the console is reading...

```
6:59:38 PM
FileSystem.documentDirectory: file:///Users/user01/Library/Developer/CoreSimulator/Devices/4D70CCEF-3FA6-4A1B-9DBF-74564A8C1D92/data/Containers/Data/Application/8FA255B6-9F57-4909-9312-7B53FFE25411/Documents/ExponentExperienceData/%2540kintyreinternal%252Flxu/
6:59:39 PM
reading parent directory
6:59:39 PM
parent contents: 0.2.5
6:59:39 PM
directory found
6:59:39 PM
checking for good downloads
6:59:39 PM
found good downloads
6:59:39 PM
found good downloads
6:59:39 PM
Object {
  "ops": Array [
    Object {
      "attributes": Object {
        "bold": true,
        "italic": true,
        "underline": true,
      },
      "insert": "BOLDITALICUNDERLINE",
    },
    Object {
      "insert": "",
    },
  ],
}
6:59:39 PM
WebViewQuillViewer: sending message SET_CONTENTS
```

Here's what the output looks like...
![output](https://user-images.githubusercontent.com/24939940/36940688-64cf606a-1f16-11e8-9197-8d700265ae01.jpeg)
I even tried using an onLoad callback with this in it...
```
setTimeout(() => this.webViewQuillViewer.sendContentToViewer(this.state.myxInput), 1000)
```

And after one second the last line of the console output repeats, but nothing is displayed in the viewer.

What am I missing?

**Comment by jacklinton** [comment]
Here's what the editor looks like, which functions perfectly
```
import React, {Component} from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { Constants } from 'expo';
import { WebViewQuillEditor } from 'react-native-webview-quilljs';


// example content to display
const contentToDisplay = {
    ops: [{ insert: 'Hello\n' }, { insert: 'This is another line' }]
};

export default class RTEditor extends Component {
    constructor(props) {
        super(props);
        this.state = {
            messageDelta: {}
        };
        console.log(this.props);
    }

    getEditorDelta = () => {
        this.webViewQuillEditor.getDelta();
    };

    getDeltaCallback = delta => {
        console.log('getDeltaCallback');
        console.log(delta);
        let deltaString = JSON.stringify(delta);
        this.props.navigation.state.params.getStateFromEditor(deltaString);
        console.log(this.props.navigation.state.params.myxInput);
    };

    render() {
        return (
            <View
                style={{
                    ...StyleSheet.absoluteFillObject,
                    backgroundColor: '#e2e2e2'
                }}
            >
                <View style={styles.statusBar} />
                <Text
                    style={{
                        paddingHorizontal: 10,
                        paddingVertical: 5,
                        fontSize: 20,
                        backgroundColor: '#9be1ff',
                        color: 'black'
                    }}
                >
                    React Native Webview Quill-js
                </Text>
                <View
                    style={{
                        flex: 1,
                        padding: 5
                    }}
                >
                    <WebViewQuillEditor
                        ref={component => (this.webViewQuillEditor = component)}
                        getDeltaCallback={this.getDeltaCallback}
                        contentToDisplay={contentToDisplay}
                    />
                </View>
                <View
                    style={{
                        margin: 5
                    }}
                >
                    <Button
                        onPress={this.getEditorDelta}
                        title="Submit"
                        color="#841584"
                        accessibilityLabel="Learn more about this purple button"
                    />
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#ccccff',
        display: 'flex'
    },
    statusBar: {
        height: Constants.statusBarHeight,
        backgroundColor: '#9be1ff'
    }
});
```

**Comment by jacklinton** [comment]
I did just update to your latest push to NPM. It seems the output from the editor has changed (ie the "inserts" are there now -
console:
```
Webview loaded
7:21:39 PM
Object {
  "ops": Array [
    Object {
      "insert": "Hello
",
    },
    Object {
      "insert": "This is another line",
    },
  ],
}
7:22:19 PM
getDeltaCallback
7:22:19 PM
Object {
  "delta": Object {
    "ops": Array [
      Object {
        "attributes": Object {
          "bold": true,
          "italic": true,
          "underline": true,
        },
        "insert": "ITALICUNDERLINEBOLD",
      },
      Object {
        "insert": "
",
      },
    ],
  },
  "type": "success",
}
7:22:19 PM
{"type":"success","delta":{"ops":[{"attributes":{"underline":true,"italic":true,"bold":true},"insert":"ITALICUNDERLINEBOLD"},{"insert":"\n"}]}}

{"ops":[{"attributes":{"bold":true,"italic":true,"underline":true},"insert":"BOLDITALICUNDERLINE"},{"insert":""}]}
```

**Comment by jacklinton** [comment]
Still can't get anything in the viewer.

**Comment by reggie3** [comment]
What does this.state.myxInput contain?  I'm not sure why you're using `JSON.parse` in your initial post.

Try this: put this in the same file as your viewer:
```
const contentToDisplay = {
  ops: [{ insert: 'Hello\n' }, { insert: 'This is another line' }]
};
```
and then set the `contentToDisplay` property of the viewer to
```
contentToDisplay ={contentToDisplay }
```
It is a properly formatted bit of content for the viewer to display.  If the viewer displays it then it'll confirm that the problem is the format of the content you're trying to display in the viewer.  You can read more about the format [here](https://github.com/quilljs/delta)

**Comment by jacklinton** [comment]
I tried taking out the conditional that prevented the viewer from loading until the api responded and changed the state. So the viewer now loads at the same time as the rest of the page, but there's still no change in behavior yet, even using the constant you gave in contentToDisplay.

**Comment by reggie3** [comment]
Yes, the viewer and editor can operate independently.  You just have to make sure you're feeding the viewer the information in the correct format.  What kind of device are you using?

**Comment by reggie3** [comment]
I see now that your original content should display the text "BOLDITALICUNDERLINE", so I think the Viewer is doing its job.
I think your Viewer might not be visible, so try setting the background color of the View containing the Viewer to a color like red to confirm that the View is actually being rendered.
Also, I'm not familiar with the "this.state.apiRes && " statement.  Can you tell me what it does?

**Comment by jacklinton** [comment]
Like I said in my previous post, I took out that conditional and it still won't display the object you gave me to try. What it does is keep the viewer from loading until the API sends back something. this.state.apiRes is null until the the response comes back from the API and setstate is called to change it to true. Once it's truthy, the whole statement is truthy and the viewer renders. If I tried to render the viewer before the API sent the thing to be displayed, the app crashed. It was a necessity of the proptypes you setup.

That yellow box is the viewer. There's no yellow box in the layout of the screen. I just pulled your latest update and it has a fatal error during bundling. I tried emptying the node_modules thread and clearing all the caches and reinstalling and it still won't bundle.

**Comment by reggie3** [comment]
Thanks for the heads up, there are some issues with the most recent published build.  I'm trying to fix those now.  However, I'm not sure what is causing the original problem.  I could be related to to the updates I've been trying to do today.  I'll keep working on it and see if I can get it working with my separate project.

**Comment by jacklinton** [comment]
Thanks for taking a look at it and for all your work on this. I wish I could help you more but I’m totally lost with how this HTML viewer works. I’ll try to study up and see if I can’t help do some of the debugging. This is the only Expo friendly RTE so to me and I’m sure others it’s more than just a “nice to have”. If I can’t get this working I’m going to have to eject from Expo, and at this stage of the project, its so early on that I’d rather just put the time in and get this one working. 

Thanks again for your hard work for being available on a Saturday night! I’ll try to get back into it tomorrow and I’ll update you if I can make some headway. Some of the problems I’m having could be NPM/Expo XDE related because even after I uninstalled the package, reinstalled the whole module library and cleared all the caches… XDE was saying “I can’t find this QuillsJS package” that I had clearly just removed. Living the life!

**Comment by reggie3** [comment]
Thanks for understanding.  I went and reverted the project back to the last working version that downloads the required HTML and JS files.  Hopefully, that is what was causing the problem, and it works for you.

**Comment by jacklinton** [comment]
If I'm following the logic correctly, the last feedback we're getting is `console.log(`WebViewQuillViewer: sending message ${type}`);` from around line 83 of the WebView...js.

It looks like the next thing is essentially sending an html request to webview, so I'm going to assume that is where the problem lies. Either the going or the coming back from the HTML request there must be some kink in the communication pipeline. That's where I'm going to start looking anyway.

**Comment by reggie3** [comment]
I think I may have found what caused the original problem.  There was a problem with the format of the data "package" containing the content that the Viewer was receiving.  I've published an npm package with the tag 'send-content-fix' which I hope solves the problem.  Can you try installing that and telling me what happens?

**Comment by jacklinton** [comment]
Well, I confirmed something. The editor component works as it should. The response from the API will display in the editor after being parsed into json and then selecting the delta. `JSON.parse(this.state.messageDelta).delta`

Here's a screen shot:
![editor](https://user-images.githubusercontent.com/24939940/36959787-e3b289e2-2011-11e8-849d-431d84d26ffa.jpeg)

But if I replace it with a viewer...
![viewer](https://user-images.githubusercontent.com/24939940/36959903-891bf666-2012-11e8-9255-f5e21c4358fd.jpeg)

So the issue is specifically with the viewer component. I think it'd be ideal to just have one component, the editor, and if you want to make it into a view just pass the appropriate props to hide the toolbar and make it read-only. That's what I would do anyway. Or create a prop to pass that you can choose 'editor' or 'viewer' when you're rendering the component.

**Comment by jacklinton** [comment]
Look at reactQuillViewer.js line 121 and how it differs from line 146 in the corresponding Editor file.
```this.state.editor.setContents(msgData.payload.ops);```
vs
```this.state.editor.setContents(msgData.payload.delta);```

Change line 121 to say delta and I suspect it will work.

**Comment by jacklinton** [comment]
I changed the config in my project to read from local files and edited that file and violà:
![workviewer](https://user-images.githubusercontent.com/24939940/36997433-9a092c94-2087-11e8-9dad-9bcb8b4eb7f2.jpeg)

**Comment by jacklinton** [comment]
I also had to change the webViewLoaded method in WebViewQuillViewer.js, which really may have been the more important part. The object you were sending to the webview in that method added an extra later of "payload" to the data the webview was looking at.

It's possible that by changing line 121 in the viewer bundle to `this.state.editor.setContents(msgData.payload.payload.ops);` would have worked as well without having to change that method.

I changed it from 
```
this.sendMessage('SET_CONTENTS', {
        payload: {
          delta: this.props.contentToDisplay.ops
        }'
```
 to
```
this.sendMessage('SET_CONTENTS', {
          delta: this.props.contentToDisplay
      });
```

Which basically just mimicked what the editor was doing in that method.

**Comment by jacklinton** [comment]
Ah I see now that you updated that function yesterday! Have you pushed it to npm yet?

**Comment by jacklinton** [comment]
I tried the new version and you're almost there. You have to take the '.ops' of of the end of 
```
this.sendMessage('SET_CONTENTS', {
          ops: this.props.contentToDisplay.ops
      });
```

**Comment by reggie3** [comment]
Thanks for trouble shooting that. I just published a new version @alpha that includes your change. Please try it and let me know if it works.

**Comment by jacklinton** [comment]
Cool. I will try it and get back to you. I'm kind of frustrated they pushed back the release of Expo 26. It seems like some of the updates to the asset bundling would make a lot of the complexity here unnecessary.

I'm about to test your versioned file downloader package too! Great work with that. If the community can streamline WebViews it will open up the Expo and React Native community to a huge amount of the standard React packages. Especially for Expo since React packages are all pure JS.

**Comment by reggie3** [comment]
@jacklinton Let me know what issues you run into with versioned-file-downloader in its issue tracker.  I'd like to "harden" its operation so that the user can handle errors gracefully.

**Comment by reggie3** [comment]
@jacklinton I think I may have found a way to streamline WebViews like you mentioned above.  I believe I have it working, but I could really use somebody else's eyes on it to make sure I'm not fooling myself.  The updated version is in the `inline-javascript-3` branch, and can be installed using the @beta tag (`npm install react-native-webview-quilljs@beta`)

Do you mind giving it a try and letting me know how it works for you?

**Comment by jacklinton** [comment]
I think I will have a chance to give it a try tonight sometime. I'll let you know.

**Comment by reggie3** [comment]
Thanks, I'll keep my fingers crossed.

**Comment by bhavishhak** [comment]
@reggie3  substituting the `delta` key with `ops` in viewerLoaded function (line 77)  fixes the rendering issue on the beta branch.

**Comment by reggie3** [comment]
@bhavishhak Thanks, I'll have a look.

**Comment by reggie3** [comment]
@bhavishhak I made the change to fix the error you discovered.  It's available in the beta.
